// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product_info.proto

package product_info

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListReq struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Category             string   `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	PriceOrder           int32    `protobuf:"varint,4,opt,name=priceOrder,proto3" json:"priceOrder,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListReq) Reset()         { *m = ListReq{} }
func (m *ListReq) String() string { return proto.CompactTextString(m) }
func (*ListReq) ProtoMessage()    {}
func (*ListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a4d768ec9cb4951, []int{0}
}

func (m *ListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReq.Unmarshal(m, b)
}
func (m *ListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReq.Marshal(b, m, deterministic)
}
func (m *ListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReq.Merge(m, src)
}
func (m *ListReq) XXX_Size() int {
	return xxx_messageInfo_ListReq.Size(m)
}
func (m *ListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListReq proto.InternalMessageInfo

func (m *ListReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListReq) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ListReq) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *ListReq) GetPriceOrder() int32 {
	if m != nil {
		return m.PriceOrder
	}
	return 0
}

type ProductProfile struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category             string   `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Price                float32  `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Title                string   `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductProfile) Reset()         { *m = ProductProfile{} }
func (m *ProductProfile) String() string { return proto.CompactTextString(m) }
func (*ProductProfile) ProtoMessage()    {}
func (*ProductProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a4d768ec9cb4951, []int{1}
}

func (m *ProductProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductProfile.Unmarshal(m, b)
}
func (m *ProductProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductProfile.Marshal(b, m, deterministic)
}
func (m *ProductProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductProfile.Merge(m, src)
}
func (m *ProductProfile) XXX_Size() int {
	return xxx_messageInfo_ProductProfile.Size(m)
}
func (m *ProductProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductProfile.DiscardUnknown(m)
}

var xxx_messageInfo_ProductProfile proto.InternalMessageInfo

func (m *ProductProfile) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductProfile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProductProfile) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *ProductProfile) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ProductProfile) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type ListResp struct {
	List                 []*ProductProfile `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListResp) Reset()         { *m = ListResp{} }
func (m *ListResp) String() string { return proto.CompactTextString(m) }
func (*ListResp) ProtoMessage()    {}
func (*ListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a4d768ec9cb4951, []int{2}
}

func (m *ListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResp.Unmarshal(m, b)
}
func (m *ListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResp.Marshal(b, m, deterministic)
}
func (m *ListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResp.Merge(m, src)
}
func (m *ListResp) XXX_Size() int {
	return xxx_messageInfo_ListResp.Size(m)
}
func (m *ListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListResp proto.InternalMessageInfo

func (m *ListResp) GetList() []*ProductProfile {
	if m != nil {
		return m.List
	}
	return nil
}

type DetailReq struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailReq) Reset()         { *m = DetailReq{} }
func (m *DetailReq) String() string { return proto.CompactTextString(m) }
func (*DetailReq) ProtoMessage()    {}
func (*DetailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a4d768ec9cb4951, []int{3}
}

func (m *DetailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailReq.Unmarshal(m, b)
}
func (m *DetailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailReq.Marshal(b, m, deterministic)
}
func (m *DetailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailReq.Merge(m, src)
}
func (m *DetailReq) XXX_Size() int {
	return xxx_messageInfo_DetailReq.Size(m)
}
func (m *DetailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailReq.DiscardUnknown(m)
}

var xxx_messageInfo_DetailReq proto.InternalMessageInfo

func (m *DetailReq) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DetailResp struct {
	Profile              *ProductProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Storage              uint32          `protobuf:"varint,2,opt,name=storage,proto3" json:"storage,omitempty"`
	Description          string          `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DetailResp) Reset()         { *m = DetailResp{} }
func (m *DetailResp) String() string { return proto.CompactTextString(m) }
func (*DetailResp) ProtoMessage()    {}
func (*DetailResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a4d768ec9cb4951, []int{4}
}

func (m *DetailResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailResp.Unmarshal(m, b)
}
func (m *DetailResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailResp.Marshal(b, m, deterministic)
}
func (m *DetailResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailResp.Merge(m, src)
}
func (m *DetailResp) XXX_Size() int {
	return xxx_messageInfo_DetailResp.Size(m)
}
func (m *DetailResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailResp.DiscardUnknown(m)
}

var xxx_messageInfo_DetailResp proto.InternalMessageInfo

func (m *DetailResp) GetProfile() *ProductProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *DetailResp) GetStorage() uint32 {
	if m != nil {
		return m.Storage
	}
	return 0
}

func (m *DetailResp) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*ListReq)(nil), "product_info.ListReq")
	proto.RegisterType((*ProductProfile)(nil), "product_info.ProductProfile")
	proto.RegisterType((*ListResp)(nil), "product_info.ListResp")
	proto.RegisterType((*DetailReq)(nil), "product_info.DetailReq")
	proto.RegisterType((*DetailResp)(nil), "product_info.DetailResp")
}

func init() { proto.RegisterFile("product_info.proto", fileDescriptor_9a4d768ec9cb4951) }

var fileDescriptor_9a4d768ec9cb4951 = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4d, 0x4b, 0x33, 0x31,
	0x10, 0xc7, 0xd9, 0x6d, 0xfb, 0x6c, 0x77, 0xda, 0xa7, 0x87, 0xc1, 0x97, 0x50, 0x45, 0x96, 0x3d,
	0xf5, 0x54, 0xa4, 0x82, 0x78, 0x10, 0x4f, 0x42, 0x2f, 0x82, 0x25, 0x5f, 0x40, 0xd6, 0xdd, 0xb4,
	0x04, 0xb6, 0x4d, 0x4c, 0xc6, 0x83, 0xe2, 0xc1, 0xa3, 0x1f, 0x5b, 0x92, 0xb4, 0x75, 0x17, 0x8a,
	0xde, 0x66, 0xfe, 0xf9, 0x27, 0xbf, 0x79, 0x09, 0xa0, 0x36, 0xaa, 0x7a, 0x2d, 0xe9, 0x49, 0x6e,
	0x96, 0x6a, 0xaa, 0x8d, 0x22, 0x85, 0xc3, 0xa6, 0x96, 0xaf, 0x21, 0x79, 0x90, 0x96, 0xb8, 0x78,
	0x41, 0x84, 0xae, 0x2e, 0x56, 0x82, 0x45, 0x59, 0x34, 0xe9, 0x71, 0x1f, 0x3b, 0xcd, 0xca, 0x77,
	0xc1, 0xe2, 0xa0, 0xb9, 0x18, 0xc7, 0xd0, 0x2f, 0x0b, 0x12, 0x2b, 0x65, 0xde, 0x58, 0x27, 0x8b,
	0x26, 0x29, 0xdf, 0xe7, 0x78, 0x01, 0xa0, 0x8d, 0x2c, 0xc5, 0xa3, 0xa9, 0x84, 0x61, 0x5d, 0x7f,
	0xab, 0xa1, 0xe4, 0x1f, 0x30, 0x5a, 0x04, 0xfc, 0xc2, 0xa8, 0xa5, 0xac, 0x05, 0x8e, 0x20, 0x96,
	0xd5, 0x96, 0x19, 0xcb, 0xca, 0x11, 0x37, 0xc5, 0x3a, 0x10, 0x53, 0xee, 0xe3, 0x5f, 0x89, 0x47,
	0xd0, 0xf3, 0xef, 0x7b, 0x58, 0xcc, 0x43, 0xe2, 0x54, 0x92, 0x54, 0x0b, 0xd6, 0xf3, 0xf6, 0x90,
	0xe4, 0xb7, 0xd0, 0x0f, 0xcd, 0x5a, 0x8d, 0x97, 0xd0, 0xad, 0xa5, 0x25, 0x16, 0x65, 0x9d, 0xc9,
	0x60, 0x76, 0x3e, 0x6d, 0x4d, 0xaa, 0x5d, 0x23, 0xf7, 0xce, 0xfc, 0x0c, 0xd2, 0x7b, 0x41, 0x85,
	0xac, 0xdd, 0xb0, 0x7e, 0xca, 0xfe, 0xef, 0xca, 0xce, 0x3f, 0x23, 0x80, 0xdd, 0xa9, 0xd5, 0x78,
	0x0d, 0x89, 0x0e, 0x97, 0xbd, 0xe7, 0x2f, 0xc0, 0xce, 0x8c, 0x0c, 0x12, 0x4b, 0xca, 0xb8, 0x35,
	0xc4, 0xfe, 0xed, 0x5d, 0x8a, 0x19, 0x0c, 0x2a, 0x61, 0x4b, 0x23, 0x35, 0x49, 0xb5, 0xd9, 0x8e,
	0xa1, 0x29, 0xcd, 0xbe, 0x22, 0x18, 0x2e, 0x1a, 0x10, 0xbc, 0x81, 0x64, 0x2e, 0xc8, 0x75, 0x8c,
	0xc7, 0x6d, 0xfc, 0x76, 0xe5, 0xe3, 0x93, 0x43, 0xb2, 0xd5, 0x78, 0x07, 0xe9, 0x5c, 0x50, 0xe8,
	0x07, 0x4f, 0xdb, 0xa6, 0xfd, 0x0c, 0xc6, 0xec, 0xf0, 0x81, 0xd5, 0xcf, 0xff, 0xfc, 0x57, 0xbb,
	0xfa, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x97, 0xc5, 0x0a, 0xab, 0x80, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProductInfoClient is the client API for ProductInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductInfoClient interface {
	// 获取商品列表
	GetList(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListResp, error)
	// 获取商品详情
	GetDetail(ctx context.Context, in *DetailReq, opts ...grpc.CallOption) (*DetailResp, error)
}

type productInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewProductInfoClient(cc grpc.ClientConnInterface) ProductInfoClient {
	return &productInfoClient{cc}
}

func (c *productInfoClient) GetList(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListResp, error) {
	out := new(ListResp)
	err := c.cc.Invoke(ctx, "/product_info.Product_info/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productInfoClient) GetDetail(ctx context.Context, in *DetailReq, opts ...grpc.CallOption) (*DetailResp, error) {
	out := new(DetailResp)
	err := c.cc.Invoke(ctx, "/product_info.Product_info/GetDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductInfoServer is the server API for ProductInfo service.
type ProductInfoServer interface {
	// 获取商品列表
	GetList(context.Context, *ListReq) (*ListResp, error)
	// 获取商品详情
	GetDetail(context.Context, *DetailReq) (*DetailResp, error)
}

// UnimplementedProductInfoServer can be embedded to have forward compatible implementations.
type UnimplementedProductInfoServer struct {
}

func (*UnimplementedProductInfoServer) GetList(ctx context.Context, req *ListReq) (*ListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (*UnimplementedProductInfoServer) GetDetail(ctx context.Context, req *DetailReq) (*DetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDetail not implemented")
}

func RegisterProductInfoServer(s *grpc.Server, srv ProductInfoServer) {
	s.RegisterService(&_ProductInfo_serviceDesc, srv)
}

func _ProductInfo_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductInfoServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_info.Product_info/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductInfoServer).GetList(ctx, req.(*ListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductInfo_GetDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductInfoServer).GetDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_info.Product_info/GetDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductInfoServer).GetDetail(ctx, req.(*DetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductInfo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "product_info.Product_info",
	HandlerType: (*ProductInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _ProductInfo_GetList_Handler,
		},
		{
			MethodName: "GetDetail",
			Handler:    _ProductInfo_GetDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product_info.proto",
}
