// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	UserName string `json:"userName" form:"userName"`
	Password string `json:"password" form:"password"`
}

type RegisterResp struct {
	OK bool `json:"ok"`
}

type LoginReq struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type LoginResp struct {
	ID     int    `json:"id"`
	Name   string `json:"name"`
	Avatar string `json:"avatar"`
	Token  string `json:"token"`
}

type VerifyReq struct {
	Ticket string `json:"ticket"`
}

type VerifyResp struct {
	Data string `json:"data"`
}
