// Code generated by goctl. DO NOT EDIT!
// Source: product_info.proto

package server

import (
	"context"

	"Tstore/backend/product/rpc/product_info/internal/logic"
	"Tstore/backend/product/rpc/product_info/internal/svc"
	"Tstore/backend/product/rpc/product_info/product_info"
)

type ProductInfoServer struct {
	svcCtx *svc.ServiceContext
	product_info.UnimplementedProductInfoServer
}

func NewProductInfoServer(svcCtx *svc.ServiceContext) *ProductInfoServer {
	return &ProductInfoServer{
		svcCtx: svcCtx,
	}
}

//  获取商品列表
func (s *ProductInfoServer) GetList(ctx context.Context, in *product_info.ListReq) (*product_info.ListResp, error) {
	l := logic.NewGetListLogic(ctx, s.svcCtx)
	return l.GetList(in)
}

//  获取商品详情
func (s *ProductInfoServer) GetDetail(ctx context.Context, in *product_info.DetailReq) (*product_info.DetailResp, error) {
	l := logic.NewGetDetailLogic(ctx, s.svcCtx)
	return l.GetDetail(in)
}
