Name: product-api
Log:
  Level: severe
Mode: dev
Host: 0.0.0.0
Port: 8888

CacheRedis: 127.0.0.1:6379


ProductInfo:
  Etcd:
    Hosts:
    - localhost:2379
    Key: productinfo.rpc

Auth:
  AccessSecret: LeeTenon
  AccessExpire: 3600
