// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"Tstore/backend/product/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/product/list/:category/:page/:price_order",
				Handler: GetListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/product/detail/:productID",
				Handler: GetDetailHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/product/buy",
				Handler: SeckillHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
