Name: productinfo.rpc
Log:
  Level: severe
ListenOn: 127.0.0.1:8080
Etcd:
  Hosts:
  - 127.0.0.1:2379
  Key: productinfo.rpc

DataSourceName: root:1906@(127.0.0.1:3306)/store?charset=utf8mb4&parseTime=True&loc=Local