// Code generated by goctl. DO NOT EDIT!
// Source: seckill.proto

package seckillclient

import (
	"context"

	"Tstore/backend/product/rpc/seckill/seckill"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = seckill.Request
	Response = seckill.Response

	SecKill interface {
		SecKillOrder(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultSecKill struct {
		cli zrpc.Client
	}
)

func NewSecKill(cli zrpc.Client) SecKill {
	return &defaultSecKill{
		cli: cli,
	}
}

func (m *defaultSecKill) SecKillOrder(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := seckill.NewSecKillClient(m.cli.Conn())
	return client.SecKillOrder(ctx, in, opts...)
}
