// Code generated by goctl. DO NOT EDIT.
package types

type GetListReq struct {
	Category   string `json:"category"`
	PriceOrder int    `json:"price_order"`
	Page int `json:"page"`
}

type GetListResp struct {
	List interface{} `json:"list"`
}

type GetDetailReq struct {
	ID uint `json:"id"`
}

type GetDetailResp struct {
	ID          uint    `json:"id"`
	Name        string  `json:"name"`
	Category    string  `json:"category"`
	Storage     uint    `json:"storage"`
	Price       float64 `json:"price"`
	Title       string  `json:"title"`
	Description string  `json:"description"`
}

type SeckillReq struct {
	ID  uint `json:"id"`
	Num uint `json:"num"`
}

type SeckillResp struct {
	ProductID   uint    `json:"productId"`
	ProductName string  `json:"product_name"`
	Num         uint    `json:"num"`
	Price       float64 `json:"price"`
}
