// Code generated by goctl. DO NOT EDIT!
// Source: seckill.proto

package server

import (
	"context"

	"Tstore/backend/product/rpc/seckill/internal/logic"
	"Tstore/backend/product/rpc/seckill/internal/svc"
	"Tstore/backend/product/rpc/seckill/seckill"
)

type SecKillServer struct {
	svcCtx *svc.ServiceContext
	seckill.UnimplementedSecKillServer
}

func NewSecKillServer(svcCtx *svc.ServiceContext) *SecKillServer {
	return &SecKillServer{
		svcCtx: svcCtx,
	}
}

func (s *SecKillServer) SecKillOrder(ctx context.Context, in *seckill.Request) (*seckill.Response, error) {
	l := logic.NewSecKillOrderLogic(ctx, s.svcCtx)
	return l.SecKillOrder(in)
}
